export const CODE_HTTP = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  ERROR_SERVER: 500,
  BAD_GATEWAY: 502
};
export const MESSAGE = {
  NOT_FOUND: 'NOT FOUND',
  ERROR_SERVER: 'ERROR SERVER',
  NO_UPDATE: "NO UPDATE",
  UPDATE: "UPDATE",
  DELETE: "ELEMENT DELETE",
  NO_DELETE: "ELEMENT NOT DELETE",
  BAD_REQUEST: "BAD_REQUEST",
  SUCCESS: "SUCCESS",
  ERROR_ENCRYPT: "ERROR_ENCRYPT",
  USER_NOT_VERIFIED: "USER NOT VERIFIED",
  INCORRECT_CREDENTIAL: "INCORRECT CREDENTIAL",
  EXCEED_LIMIT: "EXCEED LIMIT",
  PRODUCT_EXIST: "PRODUCTO EXIST",
}